Update automerge.yml

diff --git a/.github/workflows/automerge.yml b/.github/workflows/automerge.yml
--- a/.github/workflows/automerge.yml
+++ b/.github/workflows/automerge.yml
@@ -1,11 +1,11 @@
 name: Auto-Merge-PRs
-#
+##
 # This workflow automates the merging of pull requests after they have received
 # the required approvals.
 #
 on:
   pull_request:
-    types: [opened, reopened, synchronize]
+    types: [opened, reopened, synchronize, closed]
 
 jobs:
   auto-merge:
@@ -67,7 +67,7 @@ jobs:
                 COMMENTED=true
               fi
               echo "Waiting for reviewers to be assigned..."
-              sleep 10
+              sleep 60
 
               # Check if the pull request is closed after waiting
               PR_STATE=$(gh pr view $PR_NUMBER --json state --jq '.state')
@@ -139,4 +139,44 @@ jobs:
                 PR_STATE=$(gh pr view $PR_NUMBER --json state --jq '.state')
                 if [ "$PR_STATE" == "closed" ]; then
                   echo "🛑 PR #$PR_NUMBER is closed. Stopping the process."
-                  exit
+                  exit 0
+                fi
+              fi
+            done
+
+            # If the required approvals have not been received, print a message
+            if [ "$APPROVED_COUNT" -lt "$REQUIRED_APPROVALS" ]; then
+              echo "🕰️ PR #$PR_NUMBER did not receive the required approvals within 24 hours."
+            fi
+          else
+            # If the pull request targets a different branch, print a message
+            echo "❌ PR does not target the '$BASE_BRANCH' branch. No merge action will be taken."
+          fi
+
+  manual-label:
+    runs-on: ubuntu-latest
+    if: github.event.pull_request.merged == true && github.event.pull_request.merged_by.login != 'github-actions[bot]'
+
+    steps:
+      - name: Install GitHub CLI 🔧
+        run: |
+          # Install GitHub CLI
+          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
+          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
+          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
+          sudo apt-get update
+          sudo apt-get install -y gh
+
+      - name: Authenticate GitHub CLI
+        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
+
+      - name: Add manual merge label 🔖
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          # Get the pull request number from the event
+          PR_NUMBER=$(jq -r '.pull_request.number' "$GITHUB_EVENT_PATH")
+
+          # Add the manual-merge label, create if it doesn't exist
+          gh label create "merge-manual" --color "ff0000" || true
+          gh pr edit $PR_NUMBER --add-label "merge-manual"
